name: deploy-test-report

on:
  workflow_run:
    workflows: [test]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: jest-stare
          path: jest-stare

      - name: deploy test report
        run: |
          git checkout --orphan netlify-deploy-test-report
          rsync -av --progress jest-stare ../tmp
          find . -maxdepth 1 ! -name .git ! -name . -exec rm -rf {} \;
          mv ../tmp/* .
          rm -rf ../tmp
          git add .
          git config user.email "dependabot[bot]@users.noreply.github.com"
          git config user.name "dependabot[bot]"
          COMMIT_MESSAGE="deploy: (${GITHUB_SHA})"
          git commit -m "$COMMIT_MESSAGE"
          git push origin netlify-deploy-test-report -f