name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--strict-peer-dependencies]
      - name: Build
        run: pnpm build
      - name: biome lint check
        run: pnpm lint
      - name: biome format check
        run: pnpm format:check
      - name: Test
        run: pnpm test
      - name: deploy test report
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git checkout --orphan netlify-deploy-test-report
          rsync -av --progress docs/jest-stare/* ../tmp
          find . -maxdepth 1 ! -name .git ! -name . -exec rm -rf {} \;
          mv ../tmp/* .
          rm -rf ../tmp
          git add .
          git config user.email "dependabot[bot]@users.noreply.github.com"
          git config user.name "dependabot[bot]"
          COMMIT_MESSAGE="deploy: (${GITHUB_SHA})"
          git commit -m "$COMMIT_MESSAGE"
          git push origin netlify-deploy-test-report -f
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: jest-stare
          path: ./docs/jest-stare/*